-- Add version columns for JPA optimistic locking
ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE interviews ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 0;
